Reference: https://www.cssacademy.com/blog/create-a-calculator-in-html-and-css

<!DOCTYPE html>
<div class = "calculatorDesign">0</div>
<div class = "function">
    <button class = "functions functions--operand">+</button>
    <button class = "functions functions--operand">-</button>
    <button class = "functions functions--operand">&times;</button>
    <button class = "functions functions--operand">÷</button>
    <button class = "functions">log</button>
    <button class = "functions">.</button>
    <button class = "functions">0</button>
    <button class = "functions">1</button>
    <button class = "functions">2</button>
    <button class = "functions">3</button>
    <button class = "functions">4</button>
    <button class = "functions">5</button>
    <button class = "functions">6</button>
    <button class = "functions">7</button>
    <button class = "functions">8</button>
    <button class = "functions">9</button>
    <button class = "functions">.</button>
    <button class = "functions functiond--enter">=</button>
    </div>
</div>






