<!DOCTYPE html>
<html xmlns:th="https://www.thymeleaf.org">
    <head> 
        <title>SWENG Calculator</title>
        <link href="css/invalid.css" rel="stylesheet">
    </head>
    <body>
        <div class="headerStyle">
            <h1>Invalid Expression</h1>
        </div>
        <div class="invalidText">
            <h2>Please click the link below and submit another expression</h2>
        </div>
        <div class="anotherInput">
            <h3>Click <a href="/">here</a> to submit another calculation.</h3>
        </div>
    </body>
</html>